

-- USUARIO
INSERT INTO USUARIO (NOMBRE_USU, CONTRASENA) VALUES ('1', '1');
INSERT INTO USUARIO (NOMBRE_USU, CONTRASENA) VALUES ('clientejuan', 'juan456');
INSERT INTO USUARIO (NOMBRE_USU, CONTRASENA) VALUES ('huellasadmin', 'huellas123');
INSERT INTO USUARIO (NOMBRE_USU, CONTRASENA) VALUES ('patitasadmin', 'patitas123');
COMMIT;

-- CLIENTE
INSERT INTO CLIENTE (NIF, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, PROVINCIA, CIUDAD, CALLE, CP, TELEFONO, EMAIL, ID_USUARIO)
VALUES ('12345678A', 'Ana', 'Garc�a L�pez', TO_DATE('1990-07-15', 'YYYY-MM-DD'), 'Madrid', 'Madrid', 'Calle Sol 8', '28001', '600112233', 'ana.garcia@example.com', 
        (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = '1'));

INSERT INTO CLIENTE (NIF, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, PROVINCIA, CIUDAD, CALLE, CP, TELEFONO, EMAIL, ID_USUARIO)
VALUES ('87654321B', 'Juan', 'Mart�nez Sanz', TO_DATE('1985-03-22', 'YYYY-MM-DD'), 'Valencia', 'Valencia', 'Avenida del Puerto 50', '46022', '600998877', 'juan.martinez@example.com', 
        (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = 'clientejuan'));
COMMIT;

-- PROTECTORA
INSERT INTO PROTECTORA (CIF, NOMBRE, TELEFONO, EMAIL, PROVINCIA, CIUDAD, CALLE, CP, ID_USUARIO)
VALUES ('G12345678', 'Huellas Felices', '912345678', 'info@huellasfelices.org', 'Barcelona', 'Barcelona', 'Avenida de los Gatos 20', '08001',
        (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = 'huellasadmin'));

INSERT INTO PROTECTORA (CIF, NOMBRE, TELEFONO, EMAIL, PROVINCIA, CIUDAD, CALLE, CP, ID_USUARIO)
VALUES ('G87654321', 'Patitas Contentas', '933445566', 'contacto@patitascontentas.es', 'Sevilla', 'Sevilla', 'Plaza Nueva 1', '41001',
        (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = 'patitasadmin'));

COMMIT;


-- RAZA
INSERT INTO RAZA (NOMBRE_RAZA) VALUES ('Labrador Retriever');
INSERT INTO RAZA (NOMBRE_RAZA) VALUES ('Siberian Husky');
INSERT INTO RAZA (NOMBRE_RAZA) VALUES ('Golden Retriever');
INSERT INTO RAZA (NOMBRE_RAZA) VALUES ('Mestizo');
INSERT INTO RAZA (NOMBRE_RAZA) VALUES ('Bulldog Franc�s');
COMMIT;

-- PERROS
INSERT INTO PERROS (NOMBRE, SEXO, FECHA_NACIMIENTO, ADOPTADO, FOTO, ID_PROTECTORA, ID_RAZA, DESCRIPCION_PERRO)
VALUES ('Max', 'Macho', TO_DATE('2022-01-10', 'YYYY-MM-DD'), 'N', '/assets/Imagenes/perros/max_labrador.jpg', 
        (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Huellas Felices'), 
        (SELECT ID_RAZA FROM RAZA WHERE NOMBRE_RAZA = 'Labrador Retriever'), 
        'Muy juguet�n, amigable y le encanta el agua.');

INSERT INTO PERROS (NOMBRE, SEXO, FECHA_NACIMIENTO, ADOPTADO, FOTO, ID_PROTECTORA, ID_RAZA, DESCRIPCION_PERRO)
VALUES ('Luna', 'Hembra', TO_DATE('2021-08-20', 'YYYY-MM-DD'), 'N', '/assets/Imagenes/perros/luna_husky.jpg', 
        (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Huellas Felices'), 
        (SELECT ID_RAZA FROM RAZA WHERE NOMBRE_RAZA = 'Siberian Husky'), 
        'Cari�osa, un poco t�mida al principio, activa.');

INSERT INTO PERROS (NOMBRE, SEXO, FECHA_NACIMIENTO, ADOPTADO, FOTO, ID_PROTECTORA, ID_RAZA, DESCRIPCION_PERRO)
VALUES ('Rocky', 'Macho', TO_DATE('2023-05-01', 'YYYY-MM-DD'), 'N', '/assets/Imagenes/perros/rocky_mestizo.jpg', 
        (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Patitas Contentas'), 
        (SELECT ID_RAZA FROM RAZA WHERE NOMBRE_RAZA = 'Mestizo'), 
        'Un terremoto lleno de amor, tama�o mediano.');
COMMIT;

-- PATOLOGIA
INSERT INTO PATOLOGIA (NOMBRE, DESCRIPCION_PATOLOGIA) VALUES ('Alergia Alimentaria', 'Reacci�n al�rgica a ciertos componentes de la comida.');
INSERT INTO PATOLOGIA (NOMBRE, DESCRIPCION_PATOLOGIA) VALUES ('Displasia de Cadera Leve', 'Malformaci�n leve de la articulaci�n de la cadera.');
INSERT INTO PATOLOGIA (NOMBRE, DESCRIPCION_PATOLOGIA) VALUES ('Ansiedad por Separaci�n', 'Estr�s cuando se queda solo.');
COMMIT;

-- IDENTIFICACION_PATOLOGIAS
INSERT INTO IDENTIFICACION_PATOLOGIAS (ID_PERRO, ID_PATOLOGIA, NOTAS_ESPECIFICAS)
VALUES ((SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Max'), 
        (SELECT ID_PATOLOGIA FROM PATOLOGIA WHERE NOMBRE = 'Alergia Alimentaria'), 
        'Reacciona al pollo y al grano. Dieta especial requerida.');

INSERT INTO IDENTIFICACION_PATOLOGIAS (ID_PERRO, ID_PATOLOGIA, NOTAS_ESPECIFICAS)
VALUES ((SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Luna'), 
        (SELECT ID_PATOLOGIA FROM PATOLOGIA WHERE NOMBRE = 'Ansiedad por Separaci�n'), 
        'Mejora con compa��a y rutinas estables.');
COMMIT;

-- RESERVAS_CITAS
INSERT INTO RESERVAS_CITAS (FECHA, HORA, MOTIVO, ID_CLIENTE, ID_PERRO, ID_PROTECTORA, ESTADO_CITA)
VALUES (TO_DATE('2025-08-15', 'YYYY-MM-DD'), '10:30', 'Conocer a Max para posible adopci�n', 
        (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com'), 
        (SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Max'),
        (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Huellas Felices'),
        'Confirmada');

INSERT INTO RESERVAS_CITAS (FECHA, HORA, MOTIVO, ID_CLIENTE, ID_PERRO, ID_PROTECTORA, ESTADO_CITA)
VALUES (TO_DATE('2025-08-20', 'YYYY-MM-DD'), '16:00', 'Paseo de prueba con Luna', 
        (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'juan.martinez@example.com'), 
        (SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Luna'),
        (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Huellas Felices'),
        'Pendiente');
COMMIT;

-- PETICIONES_ADOPCION
INSERT INTO PETICIONES_ADOPCION (FECHA, ESTADO, ID_CLIENTE, ID_PERRO, MENSAJE_PETICION)
VALUES (TO_DATE('2025-08-01', 'YYYY-MM-DD'), 'Pendiente', 
        (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com'), 
        (SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Luna'),
        'Me encantar�a conocer a Luna, parece la perrita ideal para mi familia. Ya tengo experiencia con huskies.');
COMMIT;

-- NOTIFICACION
INSERT INTO NOTIFICACION (MENSAJE, TIPO_NOTIFICACION, ID_ENTIDAD_RELACIONADA, ENTIDAD_TIPO)
VALUES ('Nueva petici�n de adopci�n para Luna recibida de Ana Garc�a.', 'NUEVA_PETICION', 
        (SELECT ID_PETICION FROM PETICIONES_ADOPCION 
         WHERE ID_PERRO = (SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Luna') 
           AND ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com')
           AND ROWNUM = 1), -- Asume una sola petici�n para el ejemplo
        'PETICION_ADOPCION');

INSERT INTO NOTIFICACION (MENSAJE, TIPO_NOTIFICACION, ID_ENTIDAD_RELACIONADA, ENTIDAD_TIPO)
VALUES ('Tu cita con Max para el 15/08/2025 ha sido confirmada.', 'CITA_CONFIRMADA', 
        (SELECT ID_RESERVA_CITA FROM RESERVAS_CITAS 
         WHERE ID_PERRO = (SELECT ID_PERRO FROM PERROS WHERE NOMBRE = 'Max') 
           AND ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com')
           AND ROWNUM = 1),
        'RESERVA_CITA');
COMMIT;

-- NOTIFICACIONES_RECIBIDAS
INSERT INTO NOTIFICACIONES_RECIBIDAS (ID_USUARIO, ID_NOTIFICACION, LEIDA)
VALUES ((SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = 'huellasadmin'),
        (SELECT ID_NOTIFICACION FROM NOTIFICACION WHERE MENSAJE LIKE 'Nueva petici�n de adopci�n para Luna%'),
        'N');

-- Notificaci�n para el cliente sobre la cita confirmada de Max
INSERT INTO NOTIFICACIONES_RECIBIDAS (ID_USUARIO, ID_NOTIFICACION, LEIDA)
VALUES ((SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USU = '1'),
        (SELECT ID_NOTIFICACION FROM NOTIFICACION WHERE MENSAJE LIKE 'Tu cita con Max para el 15/08/2025%'),
        'N');
COMMIT;

-- REDES_SOCIALES
INSERT INTO REDES_SOCIALES (PLATAFORMA, URL, ID_PROTECTORA)
VALUES ('Instagram', 'https://instagram.com/huellasfelices', (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Huellas Felices'));
INSERT INTO REDES_SOCIALES (PLATAFORMA, URL, ID_PROTECTORA)
VALUES ('Facebook', 'https://facebook.com/patitascontentas', (SELECT ID_PROTECTORA FROM PROTECTORA WHERE NOMBRE = 'Patitas Contentas'));
COMMIT;