-- Tabla Usuario
CREATE TABLE Usuario (
    ID_Usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Usu VARCHAR2(50) NOT NULL UNIQUE,
    Contrasena VARCHAR2(100) NOT NULL
);

-- Tabla Cliente
CREATE TABLE Cliente (
    ID_Cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Apellido VARCHAR2(100),
    Telefono VARCHAR2(20),
    Email VARCHAR2(100),
    ID_Usuario NUMBER UNIQUE,
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
);

-- Tabla Protectora
CREATE TABLE Protectora (
    ID_Protectora NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Telefono VARCHAR2(20),
    Email VARCHAR2(100),
    Direccion VARCHAR2(200),
    ID_Usuario NUMBER UNIQUE,
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
);

-- Tabla Raza
CREATE TABLE Raza (
    ID_Raza NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Raza VARCHAR2(50) NOT NULL
);

-- Tabla Perros
CREATE TABLE Perros (
    ID_Perro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Sexo VARCHAR2(10) NOT NULL,
    FechaNacimiento DATE,
    Adoptado CHAR(1) DEFAULT 'N' CHECK (Adoptado IN ('S','N')),
    Foto VARCHAR2(255),
    ID_Protectora NUMBER,
    ID_Raza NUMBER,
    FOREIGN KEY (ID_Protectora) REFERENCES Protectora(ID_Protectora),
    FOREIGN KEY (ID_Raza) REFERENCES Raza(ID_Raza),
    CHECK (Sexo IN ('Macho', 'Hembra'))
);


-- Tabla Patología
CREATE TABLE Patologia (
    ID_Patologia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100)
);

-- Relación N:M entre Perros y Patologías
CREATE TABLE Identificacion_Patologias (
    ID_Perro NUMBER,
    ID_Patologia NUMBER,
    PRIMARY KEY (ID_Perro, ID_Patologia),
    FOREIGN KEY (ID_Perro) REFERENCES Perros(ID_Perro),
    FOREIGN KEY (ID_Patologia) REFERENCES Patologia(ID_Patologia)
);

-- Tabla Reservas de Citas
CREATE TABLE Reservas_Citas (
    ID_Cita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha DATE NOT NULL,
    Hora VARCHAR2(10) NOT NULL,
    Pago NUMBER CHECK (Pago >= 3),
    ID_Cliente NUMBER,
    ID_Perro NUMBER,
    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente),
    FOREIGN KEY (ID_Perro) REFERENCES Perros(ID_Perro)
);

-- Tabla Peticiones de Adopción
CREATE TABLE Peticiones_Adopcion (
    ID_Peticion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha DATE DEFAULT SYSDATE,
    Estado VARCHAR2(20) CHECK (Estado IN ('Pendiente', 'Aceptada', 'Rechazada')),
    NIF VARCHAR2(15),
    ID_Cliente NUMBER,
    ID_Perro NUMBER,
    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente),
    FOREIGN KEY (ID_Perro) REFERENCES Perros(ID_Perro)
);

-- Tabla Notificaciones
CREATE TABLE Notificacion (
    ID_Notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha DATE DEFAULT SYSDATE,
    Descripcion VARCHAR2(255) NOT NULL,
    Estado VARCHAR2(20) DEFAULT 'No Leída' CHECK (Estado IN ('Leída', 'No Leída'))
);

-- Relación N:M entre Notificaciones y Usuarios
CREATE TABLE Notificaciones_Recibidas (
    ID_Usuario NUMBER,
    ID_Notificacion NUMBER,
    PRIMARY KEY (ID_Usuario, ID_Notificacion),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Notificacion) REFERENCES Notificacion(ID_Notificacion)
);
